### ISSUE TITLE
验证问题

### ISSUE THREAD

**Issue by ph0316** [YCL92/LowlightENR#2]
![image](https://user-images.githubusercontent.com/56188513/166913537-12f73821-5c7f-4394-be7b-407bdf170e3b.png)
您好，为什么我运行run-demo的时候只输出这一行？麻烦解答一下呢，非常感谢！
Weight file loaded: ./saves\Enhancer_final_0318-064525.pth

**Comment by YCL92** [comment]
Hi, it might be the path representation difference between windows “\”. and Linux “/“. I’ve only tested the code in Ubuntu, you might need to make some changes in order to make it executable in other operating systems.

**Comment by ph0316** [comment]
Hello, can you provide the following file or the corresponding data set？Thank you.
No such file or directory: './samples/Pixel3/noiseModel/model_params.pkl'


![image](https://user-images.githubusercontent.com/56188513/167054176-637a122f-feef-4385-94fe-d3937e870265.png)

**Comment by YCL92** [comment]
If you want to train your own noise model, you should follow [this tutorial](https://github.com/YCL92/LowlightENR#noise-model-estimation) and take some dark images by yourself. We recommend using Lightroom for capturing raw images. Currently, we only provide the pre-trained models of some devices.
