### ISSUE TITLE
I didn't find Noise Model,Need Help,

### ISSUE THREAD

**Issue by Doyle59217** [YCL92/LowlightENR#3]
Hi, You mentioned "* this repository provides noise models of 4 devices as referred to the original paper." but I did not find the corresponding noise model when running run demo. How can I solve this problem?

[Errno 2] 没有那个文件或目录: './samples/Pixel3/noiseModel/model_params.pkl'

**Comment by YCL92** [comment]
Sorry for the misunderstanding. What we provide in this repo are the pre-trained models for four cameras mentioned in the paper, not the estimated noise models. We've updated the README file.
